#	version: "3.8"
#	
#	services:
#	  mysql:
#	    image: mysql:8.0
#	    container_name: mysql8
#	    restart: always
#	    environment:
#	      MYSQL_ROOT_PASSWORD: rootpw          # 루트 비밀번호
#	      MYSQL_DATABASE: ProjectOn            # 기본 생성 DB
#	      MYSQL_USER: admin                # 일반 계정
#	      MYSQL_PASSWORD: admin         # 일반 계정 비밀번호
#	    ports:
#	      - "3307:3306"                        # ← 호스트 3307, 컨테이너 3306 (로컬 3306 충돌 방지)
#	    command:
#	      - --character-set-server=utf8mb4
#	      - --collation-server=utf8mb4_general_ci
#	    healthcheck:
#	      test: ["CMD", "mysqladmin", "ping", "-prootpw", "--silent"]
#	      interval: 10s
#	      timeout: 3s
#	      retries: 5
#	    volumes:
#	      - mysql8_data:/var/lib/mysql         # 데이터 영구 저장소 볼륨
#	
#	volumes:
#	  mysql8_data:
